//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Shifts = new HashSet<Shift>();
        }
    
        public string eventID { get; set; }
        public string eventName { get; set; }
        public string eventInfo { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public Nullable<System.DateTime> eventStartTime { get; set; }
        public Nullable<System.DateTime> eventEndTime { get; set; }
        public Nullable<System.DateTime> eventSetupTime { get; set; }
        public Nullable<System.DateTime> eventTeardownTime { get; set; }
        public Nullable<System.DateTime> eventConcessionStartTime { get; set; }
        public Nullable<System.DateTime> eventConcessionEndTime { get; set; }
        public Nullable<int> eventConcessionSlots { get; set; }
        public Nullable<System.DateTime> eventFrontDeskStartTime { get; set; }
        public Nullable<System.DateTime> eventFrontDeskEndTime { get; set; }
        public Nullable<int> eventFrontDeskSlots { get; set; }
        public string orgID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
