//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VolunteerEntities : DbContext
    {
        public VolunteerEntities()
            : base("name=VolunteerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<UserAlia> UserAlias { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_events_shifts> vw_events_shifts { get; set; }
        public virtual DbSet<vw_orgs_events_shifts> vw_orgs_events_shifts { get; set; }
        public virtual DbSet<vw_users_events_shifts> vw_users_events_shifts { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
    }
}
